### ISSUE TITLE
提个问题

### ISSUE THREAD

**Issue by d1nfinite** [jiangsir404/Audit-Learning#1]
怎么查看directoryiterator支持哪些协议，我看了下manual但是好像没找到。

**Comment by jiangsir404** [comment]
比较简单的就是每个协议都试一试， 一共就没多少协议，都在这 http://php.net/manual/zh/wrappers.php， 我自己试了下只有file:// 和 glob://  这两个文件路径协议支持

**Comment by d1nfinite** [comment]
thx，我把问题关了哈
